quarkus.littlehorse.saddle.bag.name=example-saddle-bag
quarkus.littlehorse.saddle.bag.title=Example Saddle Bag
quarkus.littlehorse.saddle.bag.description=An example saddle bag showcasing tasks with primitives, strings, structs, and type adapters
quarkus.littlehorse.saddle.bag.version=0.1.0
quarkus.littlehorse.saddle.bag.metadata.tags=test,example
quarkus.littlehorse.saddle.bag.metadata.licence=MIT
quarkus.littlehorse.saddle.bag.metadata.documentation-url=https://example.com/docs/saddle-bag
quarkus.littlehorse.saddle.bag.metadata.icon-url=https://example.com/icons/saddle-bag.png
quarkus.littlehorse.saddle.bag.metadata.support-email=support@littlehorse.io
