task.print.name=print
retry.base.interval.ms=4321
retry.max.delay.ms=5000
retry.multiplier=2.2
struct.person.name=lh-person
struct.address.name=lh-address
struct.inline-customer.name=lh-inline-customer
external.inline-struct.task.name=external-inline-struct-test-task
external.inline-struct.request.name=lh-external-request
external.inline-struct.response.name=lh-external-response
