pluginManagement {
    repositories {
        mavenLocal()
        mavenCentral()
        gradlePluginPortal()
    }
    plugins {
        id "io.quarkus" version "${quarkusVersion}"
        id "io.quarkus.extension" version "${quarkusVersion}"
        id "com.diffplug.spotless" version "${spotlessVersion}"
        id "io.github.gradle-nexus.publish-plugin" version "${nexusVersion}"
    }
}
rootProject.name = "littlehorse-quarkus-extensions"

file("extensions").listFiles().findAll { it.isDirectory() }.sort { it.name }.each { dir ->
    include(dir.name)
    project(":${dir.name}").projectDir = new File(dir, "runtime")

    include("${dir.name}-deployment")
    project(":${dir.name}-deployment").projectDir = new File(dir, "deployment")
}

file("examples").listFiles().findAll { it.isDirectory() }.sort { it.name }.each { dir ->
    include("example-${dir.name}")
    project(":example-${dir.name}").projectDir = dir
}

file("extras").listFiles().findAll { it.isDirectory() }.sort { it.name }.each { dir ->
    include(dir.name)
    project(":${dir.name}").projectDir = dir
}
