quarkus.littlehorse.gateway.oauth2.mode=NONE
quarkus.oidc.enabled=false
quarkus.http.auth.proactive=false
quarkus.http.auth.permission."permit-all".paths=/*
quarkus.http.auth.permission."permit-all".policy=permit
