name: pull-request
run-name: Check PR on branch "${{ github.head_ref }}"
on:
  workflow_dispatch:
  pull_request:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get version
        id: get_version
        run: echo "version=$(sed -n 's/^version=//p' gradle.properties)" >> $GITHUB_OUTPUT

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Format
        uses: ./.github/actions/format

  unit-tests:
    needs:
      - prepare
      - format
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ["17", "21", "25"]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Unit Tests
        uses: ./.github/actions/unit-tests
        with:
          java-version: ${{ matrix.java-version }}
          version: ${{ needs.prepare.outputs.version }}

  integration-tests:
    needs:
      - prepare
      - unit-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - littlehorse-quarkus
          - littlehorse-restful-gateway
          - littlehorse-saddle-bag
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Integration Tests
        uses: ./.github/actions/integration-tests
        with:
          project: ${{ matrix.project }}
          version: ${{ needs.prepare.outputs.version }}
