name: pull-request
run-name: Check PR on branch "${{ github.head_ref }}"
on:
  workflow_dispatch:
  pull_request:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      snapshot-version: ${{ steps.get_version.outputs.snapshot-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get snapshot version
        id: get_version
        run: echo "snapshot-version=$(cat gradle.properties | grep ^version= | cut -d'=' -f2)" >> $GITHUB_OUTPUT
  tests:
    needs:
      - prepare
    uses: ./.github/workflows/tests.yml
    with:
      version: ${{ needs.prepare.outputs.snapshot-version }}
