name: pull-request
run-name: Check PR on branch "${{ github.head_ref }}"
on:
  workflow_dispatch:
  pull_request:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get version
        id: get_version
        run: echo "version=$(sed -n 's/^version=//p' gradle.properties)" >> $GITHUB_OUTPUT

  format:
    uses: ./.github/workflows/reusable-format.yml

  tests:
    needs:
      - prepare
      - format
    strategy:
      matrix:
        project:
          - littlehorse-quarkus
          - littlehorse-restful-gateway
          - littlehorse-saddle-bag
    uses: ./.github/workflows/reusable-tests.yml
    with:
      version: ${{ needs.prepare.outputs.version }}
      project: ${{ matrix.project }}
