name: release
run-name: Release ${{ github.ref_name }}
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set_tag.outputs.tag }}
    steps:
      - name: Set Tag
        id: set_tag
        run: |
          echo "tag=$(echo $GITHUB_REF | sed -n 's/refs\/tags\/v//p')" >> $GITHUB_OUTPUT

  tests:
    uses: ./.github/workflows/tests.yml

  publish:
    runs-on: ubuntu-latest
    needs:
      - prepare
      - tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "17"
      - name: Dump version
        env:
          TAG: ${{ needs.prepare.outputs.tag }}
        run: sed -i "s/version=.*/version=${TAG}/g" gradle.properties
#      Waiting for maven migration
#      - name: Publish
#        env:
#          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
#          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSPHRASE }}
#          ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.OSSRH_USERNAME }}
#          ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.OSSRH_PASSWORD }}
#        run: ./gradlew publish
#      - name: Information
#        run: echo "::warning title=Do not forget to release the java package at Maven Central::Login at https://s01.oss.sonatype.org/"
