name: reusable-format
run-name: Format check on branch "${{ github.head_ref }}"
on:
  workflow_call:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "corretto"
          java-version: "25"
      - name: Format
        run: ./gradlew spotlessJavaCheck
