name: release
run-name: Release "${{ github.ref_name }}"
on:
  workflow_dispatch:
  push:
    branches:
      - migrate-to-central-publishing-portal

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "17"
      - name: Publish
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSPHRASE }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.OSSRH_PASSWORD }}
        run: ./gradlew runtime:publishToSonatype deployment:publishToSonatype
      - name: List of file
        if: ${{ always() }}
        run: ls ./deployment/build/libs
